### ISSUE TITLE
GlobalStyle 설정

### ISSUE THREAD

**Issue by SongNoin** [wanted-pre-onboarding-fe-team-4/week1-todo-app#12]
## 개요
GlobalStyle 파일을 만들고 프로젝트에서 쓰일 color 객체를 선언합니다

## 할 일
- [ ] GlobalStyle 설정
- [ ] color 값 객체 선언
- [ ] google font 가져오기
  - Noto Sans KR

**Comment by seongbin9786** [comment]
resolved by #13
