### ISSUE TITLE
절대경로 tsconfig baseUrl 경로 수정

### ISSUE THREAD

**Issue by SongNoin** [wanted-pre-onboarding-fe-team-4/week1-todo-app#9]
## 개요
baseUrl이 "." 일 경우 해당 import를 찾지 못하는 에러가 발생했습니다.
https://stackoverflow.com/questions/50679031/why-are-these-tsconfig-paths-not-working 참고해보니 
baseUrl을 "src"로 바꿔면 에러가 나지않는다해서 수정합니다
## 할 일

- [ ] tsconfig baseUrl "." -> "src" 로 변경

**Comment by seongbin9786** [comment]
resolved by #10
